"use client";

import { useState } from "react";
import { AUDIO_FRAMES } from "../game/audio-frames";
import type { EventDefinition } from "../game/types";
import { AssetField } from "./ContentManager";

function AudioField({value,onChange}:{value:string;onChange:(value:string)=>void}){const[uploading,setUploading]=useState(false),[error,setError]=useState("");async function upload(file?:File){if(!file)return;setUploading(true);setError("");try{const form=new FormData();form.set("file",file);const response=await fetch("/api/em/assets",{method:"POST",body:form});const data=await response.json() as {url?:string;error?:string};if(!response.ok||!data.url)throw new Error(data.error??"上传失败");onChange(data.url)}catch(cause){setError(cause instanceof Error?cause.message:"上传失败")}finally{setUploading(false)}}return <div className="audio-asset-field"><span>本段音频</span><audio src={value||undefined} controls preload="metadata"/><label className="em-upload-button">{uploading?"上传中…":"上传 MP3 / WAV / OGG / M4A"}<input type="file" accept="audio/mpeg,audio/wav,audio/ogg,audio/mp4,.m4a" disabled={uploading} onChange={event=>void upload(event.target.files?.[0])}/></label><input value={value} onChange={event=>onChange(event.target.value)} placeholder="或填写音频 URL"/>{error&&<small>{error}</small>}</div>}

export default function AudioEventEditor({value,onChange}:{value:EventDefinition;onChange:(value:EventDefinition)=>void}){const segments=value.audioSegments??[];const set=(next:typeof segments)=>onChange({...value,audioSegments:next});return <fieldset className="audio-event-config"><legend><span>音</span>音画素材段落 <button type="button" onClick={()=>set([...segments,{id:`segment-${segments.length+1}`,image:"/assets/scenes/lingxiao-hall.webp",audio:"",subtitle:"填写这一段随声音出现的字幕。"}])}>＋ 添加段落</button></legend><div className="em-form-grid"><label className="wide">结束解锁文案<input value={value.unlockTitle??value.title} onChange={event=>onChange({...value,unlockTitle:event.target.value})} placeholder="例如：月下旧梦"/></label></div><p className="audio-frame-hint">画面按 720×1280（9:16）裁剪；游戏边框外径约为素材宽高的 1.2 倍（约 864×1536）。</p><div className="audio-frame-picker">{AUDIO_FRAMES.map(frame=><button type="button" key={frame.id} className={(value.audioFrameId??"gold-phoenix")===frame.id?"selected":""} onClick={()=>onChange({...value,audioFrameId:frame.id})}><span><img src={frame.src} alt=""/></span><b>{frame.name}</b><small>{frame.tone}</small></button>)}</div>{segments.map((segment,index)=><article className="audio-segment-editor" key={`${segment.id}-${index}`}><header><strong>第 {index+1} 段</strong><input value={segment.id} onChange={event=>set(segments.map((item,i)=>i===index?{...item,id:event.target.value}:item))}/><button type="button" onClick={()=>set(segments.filter((_,i)=>i!==index))}>删除</button></header><AssetField label="中央画面" value={segment.image} aspectRatio={9/16} aspectLabel="720×1280 · 9:16" onChange={image=>set(segments.map((item,i)=>i===index?{...item,image}:item))}/><AudioField value={segment.audio} onChange={audio=>set(segments.map((item,i)=>i===index?{...item,audio}:item))}/><label>本段字幕<textarea value={segment.subtitle} onChange={event=>set(segments.map((item,i)=>i===index?{...item,subtitle:event.target.value}:item))}/></label></article>)}{!segments.length&&<div className="em-empty">尚未添加音画段落。音画事件至少需要一段图片、字幕与音频。</div>}</fieldset>}
