"use client";

import { useState } from "react";
import { GIFTS } from "../game/content";
import type { GiftDefinition } from "../game/types";
import { AssetField, type ContentStatus, type ManagedContentRecord } from "./ContentManager";
import { validateGift } from "./gift-validation";

export default function GiftManager({ records, onReload }: { records: ManagedContentRecord<GiftDefinition>[]; onReload: () => Promise<void> }) {
  const blank = (): GiftDefinition => ({ id: "new-gift", name: "新礼物", description: "填写礼物说明。", icon: "礼", tags: ["心意"], image: "/assets/gifts/gift-atlas.webp", imagePosition: "50% 50%", initialCount: 1 });
  const [open,setOpen]=useState(false), [saving,setSaving]=useState(false); const [mode,setMode]=useState<"form"|"json">("form"); const [status,setStatus]=useState<ContentStatus>("published"); const [draft,setDraft]=useState<GiftDefinition>(blank); const [json,setJson]=useState(""); const [errors,setErrors]=useState<string[]>([]);
  const ids=new Set(records.map(item=>item.id)); const items=[...GIFTS.filter(item=>!ids.has(item.id)).map(definition=>({definition,origin:"builtin" as const,status:"builtin" as const,sourceMode:"code" as const})),...records.map(item=>({...item,origin:"managed" as const}))];
  function begin(definition?:GiftDefinition,itemStatus:"builtin"|ContentStatus="published",sourceMode:"code"|"form"|"json"="form"){ const next=structuredClone(definition??blank()); if(itemStatus==="builtin"){next.id=`${next.id}.variant`;next.name+= "·改";} setDraft(next);setStatus(itemStatus==="draft"?"draft":"published");setMode(sourceMode==="json"?"json":"form");setJson(JSON.stringify(next,null,2));setErrors([]);setOpen(true); }
  async function save(){setSaving(true);setErrors([]);try{const value=mode==="json"?JSON.parse(json):draft;const checked=validateGift(value);if(!checked.valid||!checked.gift){setErrors(checked.errors);return;}const response=await fetch("/api/em/gifts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({definition:checked.gift,status,sourceMode:mode})});const data=await response.json() as {error?:string;errors?:string[]};if(!response.ok)throw new Error(data.errors?.join("\n")||data.error||"保存失败");setOpen(false);await onReload();}catch(error){setErrors(String(error instanceof Error?error.message:error).split("\n"));}finally{setSaving(false)}}
  async function remove(id:string,name:string){if(!window.confirm(`确定删除“${name}”吗？`))return;await fetch(`/api/em/gifts?id=${encodeURIComponent(id)}`,{method:"DELETE"});await onReload();}
  return <section className="em-library"><div className="em-library-heading"><div><p>GIFT LIBRARY</p><h2>礼物管理器</h2><span>主图、初始持有数量、标签和说明会直接进入游戏行囊</span></div><button className="primary" onClick={()=>begin()}>＋ 新增礼物</button></div>
    <div className="em-library-grid gift-library">{items.map(item=><article key={item.definition.id}><div className="em-library-image gift-library-image" style={{backgroundImage:`url(${item.definition.image})`,backgroundPosition:item.definition.imagePosition??"center",backgroundSize:item.definition.image.includes("gift-atlas")?"500% 100%":"cover"}}><span className={item.status}>{item.status==="builtin"?"内置":item.status==="published"?"游戏中":"草稿"}</span></div><div className="em-library-copy"><small>{item.definition.id}</small><h3>{item.definition.name}</h3><p>初始 × {item.definition.initialCount} · {item.definition.tags.join(" · ")}</p><div><button onClick={()=>begin(item.definition,item.status,item.sourceMode)}>{item.origin==="builtin"?"复制改编":"编辑"}</button>{item.origin==="managed"&&<button className="danger" onClick={()=>remove(item.definition.id,item.definition.name)}>删除</button>}</div></div></article>)}</div>
    {open&&<div className="em-overlay" onMouseDown={()=>setOpen(false)}><section className="em-content-editor" onMouseDown={event=>event.stopPropagation()}><header><div><p>礼物资料卡</p><h2>{draft.name}</h2></div><button onClick={()=>setOpen(false)}>×</button></header><div className="em-editor-tabs"><button className={mode==="form"?"active":""} onClick={()=>setMode("form")}>表单录入</button><button className={mode==="json"?"active":""} onClick={()=>{setJson(JSON.stringify(draft,null,2));setMode("json")}}>结构体注入</button></div>{mode==="json"?<div className="em-json-editor"><div><strong>GiftDefinition</strong><span>可直接粘贴礼物结构体</span></div><textarea value={json} onChange={event=>setJson(event.target.value)} spellCheck={false}/></div>:<div className="em-content-form"><AssetField label="礼物主图" value={draft.image} onChange={image=>setDraft({...draft,image})}/><div className="em-form-grid"><label className="wide">唯一 ID<input value={draft.id} onChange={event=>setDraft({...draft,id:event.target.value})}/></label><label>名称<input value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></label><label>发布状态<select value={status} onChange={event=>setStatus(event.target.value as ContentStatus)}><option value="published">保存后进入游戏</option><option value="draft">仅保存草稿</option></select></label><label>图标字<input value={draft.icon} maxLength={2} onChange={event=>setDraft({...draft,icon:event.target.value})}/></label><label>初始数量<input type="number" min={0} max={999} value={draft.initialCount} onChange={event=>setDraft({...draft,initialCount:Number(event.target.value)})}/></label><label className="wide">说明<textarea value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label><label>标签<small>使用中文逗号分隔</small><input value={draft.tags.join("，")} onChange={event=>setDraft({...draft,tags:event.target.value.split(/[，,]/).map(v=>v.trim()).filter(Boolean)})}/></label><label>主图定位<input value={draft.imagePosition??"center"} onChange={event=>setDraft({...draft,imagePosition:event.target.value})}/></label></div></div>}{errors.length>0&&<div className="em-errors">{errors.map((error,index)=><p key={`${error}-${index}`}>· {error}</p>)}</div>}<footer><button className="quiet" onClick={()=>setOpen(false)}>取消</button><button className="primary" disabled={saving} onClick={save}>{saving?"保存中…":"保存礼物"}</button></footer></section></div>}
  </section>;
}
