"use client";

import type { CSSProperties } from "react";
import { type DailyCommission, type ProductStack, MUTATIONS, getMutationValue, matchesFuzzyCommission, mutationDisplayName, productStackKey } from "./commissions";
import type { GameItem } from "./item-data";
import { MATERIALS, PRODUCTS } from "./item-data";
import { MARKET_QUALITY_WEIGHTS, getMarketPrice, type MarketOffer } from "./market";

export type ProductEntry = { stack: ProductStack; item: GameItem };

export function AlchemyMarketOverlay(props: {
  open: boolean; onClose: () => void; gold: number; tab: "goods" | "commissions"; onTab: (tab: "goods" | "commissions") => void;
  marketItems: Array<{ offer: MarketOffer; item: GameItem }>; marketReady: boolean; marketSoldOut: boolean; soldOutRemaining: string; manualRefreshCount: number; manualResetRemaining: string; manualRefreshPrice: number; onRefresh: () => void; onInspectOffer: (offer: MarketOffer, item: GameItem) => void; onBuy: (id: string) => void;
  commissions: DailyCommission[]; commissionRefreshAt: number; commissionRemaining: string; commissionStock: (commission: DailyCommission) => number; selectedEntries: (id: string) => ProductEntry[]; commissionReward: (commission: DailyCommission) => number; onInspectCommission: (commission: DailyCommission, item: GameItem | null, stock: number, reward: number) => void; onRemoveSelection: (id: string, index: number) => void; onPickSelection: (id: string) => void; onDeliver: (commission: DailyCommission) => void; productEntries: ProductEntry[];
}) {
  if (!props.open) return null;
  return <div className="market-overlay" role="dialog" aria-modal="true" aria-label="云游集市"><div className="market-window">
    <header className="market-heading"><div><span>浮 云 有 市 · 奇 珍 自 来</span><h2>云游集市</h2><p>每轮六件灵材，售罄后十息自动补货</p></div><div className="market-wallet"><small>持有灵石</small><strong><i>◉</i>{props.gold.toLocaleString()}</strong></div><button className="market-close" onClick={props.onClose} aria-label="关闭集市">×</button></header>
    <div className="market-odds" aria-label="品质出现概率">{props.tab === "goods" ? (Object.entries(MARKET_QUALITY_WEIGHTS) as [string, number][]).map(([quality, weight]) => <span key={quality} className={`quality-text quality-${quality}`}><i />{quality} {weight}%</span>) : <><span>指定委托 5 条</span><span>模糊委托 2 条</span><span>低品质需求更常见</span><span>收购价高于市价</span></>}</div>
    <nav className="market-tabs" aria-label="集市功能"><button className={props.tab === "goods" ? "active" : ""} onClick={() => props.onTab("goods")}>灵材摊位</button><button className={props.tab === "commissions" ? "active" : ""} onClick={() => props.onTab("commissions")}>仙门委托 <b>{props.commissions.length}</b></button></nav>
    {props.tab === "goods" ? <>
      <div className="market-grid">{props.marketItems.map(({ offer, item }, index) => <article key={offer.id} role="button" tabIndex={0} onClick={() => props.onInspectOffer(offer, item)} className={`market-card quality-${item.quality} ${offer.sold ? "sold" : ""}`} style={{ "--item-color": item.color } as CSSProperties}><span className="market-stock">货位 {String(index + 1).padStart(2, "0")}</span><span className="market-quality">{item.quality}</span><div className="market-item-art"><img src={item.image} alt="" /></div><div className="market-item-copy"><strong>{item.name}</strong><small>{item.attribute} · {item.trait}</small></div><div className="market-price"><span><i>◉</i>{getMarketPrice(item).toLocaleString()}</span><button onClick={(event) => { event.stopPropagation(); props.onBuy(offer.id); }} disabled={offer.sold}>{offer.sold ? "已售罄" : "购 入"}</button></div>{offer.sold && <div className="sold-seal">售罄</div>}</article>)}{!props.marketReady && <div className="market-loading">云商正在布置货架……</div>}</div>
      <footer className="market-footer"><div className="market-rule-copy"><strong>{props.marketSoldOut ? `全场售罄 · ${props.soldOutRemaining} 后自动补货` : "货品一经购入，将直接进入乾坤灵囊"}</strong><small>{props.manualRefreshCount > 0 ? `${props.manualResetRemaining} 后刷新费用恢复免费` : "当前拥有一次免费刷新机会"}</small></div><button className="market-refresh" onClick={props.onRefresh} disabled={!props.marketReady}><span>↻</span><b>刷新货架</b><small>{props.manualRefreshPrice === 0 ? "本次免费" : `${props.manualRefreshPrice.toLocaleString()} 灵石`}</small></button></footer>
    </> : <>
      <div className="commission-workspace"><section className="commission-list" aria-label="仙门售卖委托">{props.commissions.map((commission, index) => { const item = commission.kind === "specific" ? [...MATERIALS, ...PRODUCTS].find((candidate) => candidate.id === commission.itemId) ?? null : null; const stock = props.commissionStock(commission); const name = commission.kind === "specific" ? item?.name ?? "未知货品" : commission.title; const entries = commission.kind === "fuzzy" ? props.selectedEntries(commission.id) : []; const reward = props.commissionReward(commission); return <article key={commission.id} role="button" tabIndex={0} onClick={() => props.onInspectCommission(commission, item, stock, reward)} className={`commission-card ${commission.kind}`}><span className="commission-index">{String(index + 1).padStart(2, "0")}</span><div className="commission-icon">{item ? <img src={item.image} alt="" /> : <span>{commission.kind === "fuzzy" && commission.requirement === "element" ? commission.element : "品"}</span>}</div><div className="commission-copy"><small>{commission.kind === "specific" ? `${item?.itemType === "material" ? "材料救急回收" : "丹药加工委托"}` : `模糊丹药委托 · ${commission.pricingMode === "dynamic" ? "动态价格" : "仙门定价"}`}</small><strong>{name} ×{commission.quantity}</strong><em>{commission.kind === "fuzzy" ? `已装填 ${stock}/${commission.quantity}` : `持有 ${stock}/${commission.quantity}`}</em></div>{commission.kind === "fuzzy" && <div className="fuzzy-item-slots" aria-label={`${commission.title}物品框`}>{Array.from({ length: commission.quantity }).map((_, slotIndex) => { const entry = entries[slotIndex]; return <button key={slotIndex} className={entry ? "filled" : ""} onClick={() => entry ? props.onRemoveSelection(commission.id, slotIndex) : props.onPickSelection(commission.id)} aria-label={entry ? `移除${mutationDisplayName(entry.item, entry.stack.mutation)}` : `选择第${slotIndex + 1}件丹药`}>{entry ? <><img src={entry.item.image} alt="" /><span>{MUTATIONS[entry.stack.mutation].prefix || entry.item.element}</span></> : <><b>＋</b><span>选丹</span></>}</button>; })}</div>}<div className="commission-reward"><small>{commission.kind === "specific" && item?.itemType === "material" ? "救急档回收" : commission.kind === "fuzzy" && commission.pricingMode === "dynamic" ? "总估值 ×1.5" : "完整劳作奖励"}</small><strong>◉ {reward.toLocaleString()}</strong></div><button onClick={(event) => { event.stopPropagation(); props.onDeliver(commission); }} disabled={stock < commission.quantity}>交 付</button></article>; })}{props.commissions.length === 0 && <div className="commission-empty">{props.commissionRefreshAt <= 0 ? "委托正在送达……" : "本轮委托均已完成"}</div>}</section>
      <aside className="product-vault"><header><span>炼 成 物</span><h3>成品库</h3><small>{props.productEntries.length} 个独立格</small></header><div>{props.productEntries.map(({ stack, item }) => <article key={productStackKey(stack.productId, stack.mutation)} className={`mutation-${stack.mutation}`}><img src={item.image} alt="" /><span><strong>{mutationDisplayName(item, stack.mutation)}</strong><small>{MUTATIONS[stack.mutation].note} · 估值 {getMutationValue(item, stack.mutation).toLocaleString()}</small></span><b>×{stack.count}</b></article>)}</div>{props.productEntries.length === 0 && <p>尚无成品，先去丹炉炼制一炉。</p>}</aside></div>
      <footer className="market-footer commission-footer"><div className="market-rule-copy"><strong>委托榜将在 {props.commissionRemaining} 后刷新</strong><small>纯采购仅按救急价回收；炼制、品质与调查委托才提供完整奖励</small></div><span className="commission-seal">劳动留痕 · 价格锁定</span></footer>
    </>}
  </div></div>;
}

export function FuzzyPickerOverlay({ commission, selections, products, reward, onPick, onClose }: { commission: Extract<DailyCommission, { kind: "fuzzy" }> | null; selections: string[]; products: ProductEntry[]; reward: number; onPick: (key: string) => void; onClose: () => void }) {
  if (!commission) return null;
  const eligible = products.filter(({ item }) => matchesFuzzyCommission(item, commission));
  return <div className="fuzzy-picker-overlay" role="dialog" aria-modal="true" aria-label="选择符合委托的丹药"><button className="fuzzy-picker-backdrop" onClick={onClose} aria-label="关闭配货" /><section className="fuzzy-picker"><header><div><span>乾 坤 灵 囊 · 成 品 库</span><h2>为「{commission.title}」配货</h2><p>已选 {selections.length}/{commission.quantity} · 点击丹药放入空物品框</p></div><button onClick={onClose} aria-label="关闭">×</button></header><div className="fuzzy-picker-summary"><span className={commission.pricingMode === "dynamic" ? "dynamic" : "fixed"}>{commission.pricingMode === "dynamic" ? "动态价格" : "仙门定价"}</span><strong>{commission.pricingMode === "dynamic" ? `当前结算 ◉ ${reward.toLocaleString()}` : `固定酬金 ◉ ${commission.reward.toLocaleString()}`}</strong><small>{commission.pricingMode === "dynamic" ? "所选物品总估值 ×1.5" : "物品成色不会改变本单酬金"}</small></div><div className="fuzzy-picker-grid">{eligible.map(({ stack, item }) => { const key = productStackKey(stack.productId, stack.mutation); const selectedCount = selections.filter((selectedKey) => selectedKey === key).length; const unavailable = selectedCount >= stack.count || selections.length >= commission.quantity; return <button key={key} className={`fuzzy-picker-item mutation-${stack.mutation}`} onClick={() => onPick(key)} disabled={unavailable}><span className="fuzzy-picker-art"><img src={item.image} alt="" /></span><span><strong>{mutationDisplayName(item, stack.mutation)}</strong><small>{item.element} · {item.quality} · 估值 {getMutationValue(item, stack.mutation).toLocaleString()}</small></span><b>{selectedCount > 0 ? `已选 ${selectedCount}/` : "持有 "}{stack.count}</b></button>; })}{eligible.length === 0 && <p className="fuzzy-picker-empty">成品库中暂时没有符合条件的丹药。</p>}</div><footer><button onClick={onClose}>完成配货</button></footer></section></div>;
}

export function AlchemyCodexOverlay({ open, rows, search, filter, filters, groupCount, onSearch, onFilter, onExport, onClose }: { open: boolean; rows: GameItem[]; search: string; filter: string; filters: string[]; groupCount: number; onSearch: (value: string) => void; onFilter: (value: string) => void; onExport: () => void; onClose: () => void }) {
  if (!open) return null;
  return <div className="codex-overlay" role="dialog" aria-modal="true" aria-label="万物图鉴属性表"><div className="codex-window"><header className="codex-heading"><div><span>太虚万物志 · 数据总览</span><h2>{MATERIALS.length + PRODUCTS.length} 项材料与成品</h2></div><button onClick={onClose} aria-label="关闭万物图鉴">×</button></header><div className="codex-summary"><div><strong>{MATERIALS.length + PRODUCTS.length}</strong><span>图鉴总数</span></div><div><strong>{MATERIALS.length}</strong><span>可炼制材料</span></div><div><strong>{PRODUCTS.length}</strong><span>不可炼制成品</span></div><div><strong>{groupCount}</strong><span>素材系列</span></div></div><div className="codex-toolbar"><label><span>⌕</span><input value={search} onChange={(event) => onSearch(event.target.value)} placeholder="搜索名称、五行或效果" aria-label="搜索图鉴" /></label><div>{filters.map((name) => <button key={name} className={filter === name ? "active" : ""} onClick={() => onFilter(name)}>{name}</button>)}</div><button className="export-button" onClick={onExport}>导出属性表</button></div><div className="codex-table-wrap"><table><thead><tr><th>序</th><th>图鉴</th><th>名称</th><th>类型</th><th>归属</th><th>属性</th><th>品质</th><th>特性</th><th>价格</th><th>人物缘契</th><th>玩法效果</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id} className={item.characterTrigger ? "fated-row" : ""}><td>{String(item.index).padStart(3, "0")}</td><td><img src={item.image} alt="" loading="lazy" /></td><td><strong>{item.name}</strong><small>{item.short}</small></td><td><span className={`kind-pill kind-${item.itemType}`}>{item.itemType === "material" ? "材料" : "成品"}</span><small>{item.canBeIngredient ? "可投入" : "不可炼制"}</small></td><td>{item.group ?? item.kind}·{item.category}</td><td><i style={{ background: item.color }} />{item.attribute}</td><td className={`quality-text quality-${item.quality}`}>{item.quality}<small>{"◆".repeat(item.rarity)}</small></td><td>{item.trait}</td><td>{item.price.toLocaleString()}<small>灵石</small></td><td>{item.character ? <><strong>{item.character.title}</strong><small>{item.character.relation} · 权重+{item.character.affinity}</small></> : <small>—</small>}</td><td>{item.effect}</td></tr>)}</tbody></table></div><footer>当前显示 {rows.length} 项 · 属性数据由统一表格驱动，可搜索、筛选与导出</footer></div></div>;
}
