import type { CharacterDefinition, CharacterMessageDefinition, EventDefinition, GiftDefinition, GlobalKeyDefinition, SceneDefinition } from "./types";
import { SHOP_CHARACTERS, SHOP_EVENTS, SHOP_GIFTS, SHOP_MESSAGES, SHOP_SCENES } from "./shop-content";

export const GLOBAL_KEYS: GlobalKeyDefinition[] = [
  { id: "memory.shen.hid_injury", name: "曾向沈清霜隐瞒伤势", category: "人物记忆", description: "示范由事件选项写入、并在后续对话中被人物提起的长期记忆。", initialValue: false, triggerMode: "manual", autoRules: [] },
  { id: "world.disaster_arrived", name: "灾害已经降临", category: "世界事件", description: "第 5 日后且完成至少 3 个事件时自动触发，也可被事件节点手动写入。", initialValue: false, triggerMode: "both", autoRules: [{ id: "day-five-and-three-events", label: "第五日且历经三件事", conditions: [{ type: "day_reached", min: 5 }, { type: "completed_event_count", min: 3 }] }], announcement: { enabled: true, title: "天象骤变", message: "远山阴云蔽日，宗门钟声连响九次。灾变已至，部分人物与场景可能因此发生变化。" } },
  { id: "world.tavern_ruined", name: "醉月楼已经破败", category: "场景状态", description: "示范由剧情节点手动写入后，让醉月楼切换到破败场景变体。", initialValue: false, triggerMode: "manual", autoRules: [] },
];

export const SCENES: SceneDefinition[] = [
  {
    id: "lingxiao",
    name: "凌霄殿",
    shortName: "宗门",
    description: "云海之上的宗主府，今日殿中有淡淡松香。",
    atmosphere: "云静 · 香寒",
    image: "/assets/scenes/lingxiao-hall.webp",
    characters: ["shen", "su"],
  },
  {
    id: "tavern",
    name: "醉月楼",
    shortName: "山下",
    description: "临水而建的旧酒楼，灯火总比暮色早亮一刻。",
    atmosphere: "灯暖 · 雨微",
    image: "/assets/scenes/drunken-moon-tavern.webp",
    characters: ["hua", "liu"],
    minigameDifficulty: { drinking: 4 },
    variants: [
      { id: "tavern-after-ruin", name: "醉月楼·残垣", description: "旧日灯火已经熄灭，只余被风雨侵蚀的梁柱。", atmosphere: "灯灭 · 风寒", image: "/assets/scenes/drunken-moon-tavern.webp", priority: 100, conditions: [{ type: "flag", key: "world.tavern_ruined", value: true }] },
    ],
  },
  {
    id: "market",
    name: "云州市集",
    shortName: "市集",
    description: "浮云托起百家铺面，灵石、宝器与甜香都在此处流转。",
    atmosphere: "云开 · 市喧",
    image: "/assets/scenes/yunzhou-market.webp",
    characters: ["hua"],
  },
  {
    id: "bedroom",
    name: "听云居",
    shortName: "居所",
    description: "属于你的临崖小院。月光穿过窗棂，静室中央的聚灵阵正缓缓流转。",
    atmosphere: "月静 · 灵息",
    image: "/assets/scenes/lingxiao-hall.webp",
    characters: [],
  },
  {
    id: "spirit-farm",
    name: "云岫灵圃",
    shortName: "灵圃",
    description: "宗门东麓的十二畦灵田，以山泉、天时与灵壤培育炼丹仙草。",
    atmosphere: "土润 · 药香",
    image: "/assets/maps/yunzhou-realm.webp",
    characters: [],
  },
  {
    id: "intelligence-bureau",
    name: "槐安情报局",
    shortName: "情报",
    description: "藏在云州长街深处的消息中枢，万千纸鹤昼夜衔来诸界见闻。",
    atmosphere: "灯影 · 鹤讯",
    image: "/assets/scenes/yunzhou-market.webp",
    characters: ["wenren-fei"],
  },
];

export const GIFTS: GiftDefinition[] = [
  { id: "snowTea", name: "雪芽灵茶", description: "采自寒峰，清冽回甘。", icon: "茶", tags: ["清雅", "灵气"], image: "/assets/gifts/gift-atlas.webp", imagePosition: "0% 50%", initialCount: 2 },
  { id: "peachWine", name: "十年桃花酿", description: "开坛便有春日香气。", icon: "酿", tags: ["酒", "旧忆"], image: "/assets/gifts/gift-atlas.webp", imagePosition: "25% 50%", initialCount: 2 },
  { id: "herbSachet", name: "紫苏安神囊", description: "草木温柔，能安一夜好梦。", icon: "香", tags: ["药草", "手作"], image: "/assets/gifts/gift-atlas.webp", imagePosition: "50% 50%", initialCount: 2 },
  { id: "goldHairpin", name: "金丝海棠簪", description: "细金缠花，灯下尤其好看。", icon: "簪", tags: ["华贵", "饰物"], image: "/assets/gifts/gift-atlas.webp", imagePosition: "75% 50%", initialCount: 2 },
  { id: "osmanthusCake", name: "桂花云片糕", description: "甜得克制，食用后恢复 5 点体力。", icon: "糕", tags: ["点心", "恢复"], image: "/assets/gifts/gift-atlas.webp", imagePosition: "100% 50%", initialCount: 4, energyRestore: 5 },
];

function relationshipStages(addresses: [string,string,string,string]) {
  return [
    { id: "stranger", min: 0, name: "初识", addressing: addresses[0], description: "彼此尚守着礼数与距离。" },
    { id: "familiar", min: 15, name: "相知", addressing: addresses[1], description: "她开始记住你无意间说过的话。" },
    { id: "close", min: 35, name: "心悦", addressing: addresses[2], description: "有些等待与牵挂，已经不必明言。" },
    { id: "devoted", min: 65, name: "同心", addressing: addresses[3], description: "山长水远，她仍愿与你并肩。" },
  ];
}

export const CHARACTERS: CharacterDefinition[] = [
  {
    id: "wenren-fei",
    name: "闻人绯",
    role: "槐安情报局主事",
    courtesy: "绯掌事",
    bio: "执掌万象闻壁的情报商。她能从三句闲谈里辨出两句谎话，却始终不肯透露自己的来历。",
    sceneId: "intelligence-bureau",
    image: "/assets/characters/wenren-fei-v1.png",
    accent: "#b9674f",
    lovedGift: "goldHairpin",
    relationshipStages: relationshipStages(["来客", "道友", "你", "知己"]),
    giftPreferences: [{giftId:"goldHairpin",tier:"loved",reaction:"她将金簪抵在灯下看了许久，笑说这份消息值得珍藏。"},{giftId:"peachWine",tier:"liked",reaction:"她收下酒坛，说夜深整理密卷时正用得上。"},{giftId:"snowTea",tier:"neutral",reaction:"她命人换了新水，当场沏了一盏。"}],
    ambientLines: [
      "万象闻壁上十条消息里，三条是真，六条是半真——剩下一条最值钱。",
      "你的名字今日又在问道榜上升了一位。放心，我没有替你买名次。",
      "情报局不问来路，只问消息能否经得住下一盏茶的推敲。",
    ],
  },
  {
    id: "shen",
    name: "沈清霜",
    role: "问剑峰主 · 师尊",
    courtesy: "清衡真人",
    bio: "持剑如雪，寡言守礼。她似乎总能比你更早察觉伤势。",
    sceneId: "lingxiao",
    image: "/assets/characters/shen-qingshuang.webp",
    accent: "#9bb7c9",
    lovedGift: "snowTea",
    relationshipStages: relationshipStages(["弟子", "你", "名字", "心上人"]),
    giftPreferences: [{ giftId:"snowTea",tier:"loved",reaction:"她用指腹轻轻摩挲茶罐，眼神比往常柔和。" },{ giftId:"osmanthusCake",tier:"liked",reaction:"她说甜了些，却仍将糕点收在手边。" },{ giftId:"peachWine",tier:"disliked",reaction:"她不喜酒气，只礼貌地收下了。" }],
    seekingRules: [{ id:"shen-seeks-player",label:"月下前来寻你",periods:["夜晚"],probability:45,cooldownDays:3,priority:90,conditions:[{type:"event_completed",eventId:"shen.gift.snow-tea"},{type:"relationship",characterId:"shen",min:16}],triggerEventId:"shen.heart.moon-sword",intro:"夜色将沉，沈清霜却踏着剑光来到你面前。" }],
    ambientLines: [
      "今日气息比昨日沉稳。看来你没有荒废早课。",
      "修行不必事事争先。知道何时停剑，也是一种境界。",
      "若夜里又做噩梦，便来问剑峰。山风虽冷，却很安静。",
    ],
  },
  {
    id: "su",
    name: "苏晚棠",
    role: "执事长老 · 师叔",
    courtesy: "照影仙子",
    bio: "爱酒也爱玩笑，行事看似散漫，却记得所有人的软肋。",
    sceneId: "lingxiao",
    image: "/assets/characters/su-wantang.webp",
    accent: "#a84c45",
    lovedGift: "peachWine",
    relationshipStages: relationshipStages(["小弟子", "小友", "你呀", "我的归人"]),
    giftPreferences: [{ giftId:"peachWine",tier:"loved",reaction:"她嗅到酒香便笑了，难得没有立刻开坛。" },{ giftId:"osmanthusCake",tier:"liked",reaction:"她将糕点掰成两半，示意你坐下一起吃。" },{ giftId:"snowTea",tier:"neutral",reaction:"她说清茶也好，正好醒酒。" }],
    seekingRules: [{ id:"su-seeks-player",label:"带酒来寻",periods:["黄昏","夜晚"],probability:38,cooldownDays:3,priority:85,conditions:[{type:"event_completed",eventId:"su.gift.peach-wine"},{type:"relationship",characterId:"su",min:12}],triggerEventId:"su.heart.plum-vow",intro:"一阵桃花酒香先到了，苏晚棠随后倚在门边朝你招手。" }],
    ambientLines: [
      "你师尊方才还问起你。放心，我什么都没添油加醋。",
      "宗门规矩写了三百卷，真正有用的，大约不超过三页。",
      "陪师叔饮一杯？不喝也成，坐下听故事总不会醉。",
    ],
  },
  {
    id: "liu",
    name: "柳知意",
    role: "悬壶谷医师",
    courtesy: "青蘅",
    bio: "受邀暂居醉月楼。她辨药极准，却不太擅长辨认自己的心事。",
    sceneId: "tavern",
    image: "/assets/characters/liu-zhiyi.webp",
    accent: "#89a79b",
    lovedGift: "herbSachet",
    relationshipStages: relationshipStages(["仙长", "你", "名字", "此生所念"]),
    giftPreferences: [{ giftId:"herbSachet",tier:"loved",reaction:"她逐味辨过香囊中的药草，耳尖悄悄红了。" },{ giftId:"snowTea",tier:"liked",reaction:"她说这茶适合入药，也适合与你慢慢喝。" },{ giftId:"peachWine",tier:"disliked",reaction:"她担心酒误药性，神色有些为难。" }],
    seekingRules: [{ id:"liu-seeks-player",label:"担忧旧伤",periods:["清晨","黄昏"],probability:42,cooldownDays:2,priority:88,conditions:[{type:"event_completed",eventId:"liu.gift.herb-sachet"},{type:"relationship",characterId:"liu",min:12}],triggerEventId:"liu.heart.pulse",intro:"柳知意背着药箱赶来，说只是顺路，却先伸手探你的脉。" }],
    ambientLines: [
      "伸手。不是诊脉，只是看你有没有又偷偷练到脱力。",
      "药苦并非坏事，可若有人愿意递一块糖，也会好过许多。",
      "我在窗下种了几株薄荷。下次来，或许能泡一壶新茶。",
    ],
    appearances: [{
      sceneId: "tavern",
      mode: "random",
      guaranteedRules: [
        { id: "after-first-tavern-visit", label: "初识老板娘后，医师必定现身一次", conditions: [{ type: "event_completed", eventId: "hua.first.welcome" }], triggerEventId: "liu.first.herb-basket" },
      ],
      randomRules: [
        { id: "morning-clinic", label: "清晨偶尔来楼中替人看诊", periods: ["清晨"], conditions: [], probability: 45 },
        { id: "evening-rest", label: "黄昏较常在楼中歇脚", periods: ["黄昏"], conditions: [], probability: 72 },
        { id: "night-herbs", label: "夜晚偶尔留在客房配药", periods: ["夜晚"], conditions: [], probability: 30 },
      ],
    }],
  },
  {
    id: "hua",
    name: "花照影",
    role: "醉月楼主人",
    courtesy: "花老板",
    bio: "消息与酒都卖，却从不肯为自己的往事开价。",
    sceneId: "tavern",
    image: "/assets/characters/hua-zhaoying.webp",
    accent: "#b5784d",
    lovedGift: "goldHairpin",
    relationshipStages: relationshipStages(["客官", "仙长", "你", "良人"]),
    giftPreferences: [{ giftId:"goldHairpin",tier:"loved",reaction:"她当场将簪子别入发间，问你是否好看。" },{ giftId:"peachWine",tier:"liked",reaction:"她看一眼封泥便知道年份，笑意很真。" },{ giftId:"herbSachet",tier:"neutral",reaction:"她把香囊挂在账册旁，说正好驱蚊。" }],
    seekingRules: [{ id:"hua-seeks-player",label:"闭店来寻",periods:["夜晚"],probability:40,cooldownDays:3,priority:86,conditions:[{type:"event_completed",eventId:"hua.gift.hairpin"},{type:"relationship",characterId:"hua",min:14}],triggerEventId:"hua.heart.closed-tavern",intro:"醉月楼今夜早早闭门，花照影却提着灯来寻你。" }],
    interactions:{drinking:{enabled:true,sceneIds:["tavern"],periods:["夜晚"],minRelationship:15,maxAttempts:6,targetScore:10,specialWinCount:3,specialEventId:"hua.drinking.three-cups"}},
    ambientLines: [
      "楼上那桌客人说你剑法了得。我看他们更擅长夸大其词。",
      "有些人来喝酒是为了记得，有些人是为了忘记。你是哪一种？",
      "今日不收你的酒钱。别多想，只是账本刚好翻不到那一页。",
    ],
    appearances: [
      { sceneId: "tavern", mode: "resident", guaranteedRules: [], randomRules: [] },
      { sceneId: "market", mode: "resident", guaranteedRules: [], randomRules: [] },
    ],
  },
];

export const CHARACTER_MESSAGES: CharacterMessageDefinition[] = [
  { id:"letter.shen.medicine",senderCharacterId:"shen",title:"问剑峰的药",body:"袖伤若还疼，夜里便来取药。不要又说只是小伤——你说谎时，总不敢看我。",signature:"沈清霜",conditions:[{type:"event_completed",eventId:"shen.first.snow-in-hall"}],relationshipAmount:1,giftId:"snowTea",giftAmount:1 },
  { id:"letter.su.wine",senderCharacterId:"su",title:"留一只空杯",body:"好酒要等值得的人。明日若得闲，来殿后寻我，我替你留一只杯子。",signature:"苏晚棠",conditions:[{type:"day_reached",min:2},{type:"relationship",characterId:"su",min:8}],relationshipAmount:1 },
  { id:"letter.liu.followup",senderCharacterId:"liu",title:"复诊",body:"旧伤不可只看表面。若你经过醉月楼，请让我再诊一次脉。药不苦，我备了糖。",signature:"柳知意",conditions:[{type:"event_completed",eventId:"liu.first.herb-basket"}],giftId:"osmanthusCake",giftAmount:1 },
  { id:"letter.hua.lamp",senderCharacterId:"hua",title:"临窗的位置",body:"今日临窗那张桌子仍替你留着。不是没人订，只是我觉得旁人坐着不好看。",signature:"花照影",conditions:[{type:"event_completed",eventId:"hua.first.welcome"}],relationshipAmount:1 },
];

export const EVENTS: EventDefinition[] = [
  {
    id: "shen.first.snow-in-hall",
    title: "殿上初雪",
    subtitle: "她在众人之前唤住了你",
    chapter: "沈清霜 · 壹",
    type: "相识",
    trigger: "scene_enter",
    priority: 90,
    once: true,
    journal: true,
    sceneId: "lingxiao",
    characterId: "shen",
    conditions: [{ type: "scene", value: "lingxiao" }],
    clue: "初次踏入凌霄殿",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "narrator", text: "晨雾尚未散去。殿中议事的人已经走尽，沈清霜却仍站在长阶尽头。", next: "b" },
      b: { id: "b", type: "line", speaker: "shen", text: "袖口有血。昨日又练到了几更？", mood: "担忧", next: "c" },
      c: {
        id: "c",
        type: "choice",
        prompt: "你打算如何回答？",
        options: [
          { id: "honest", label: "如实说练到了三更", next: "d", effects: [{ type: "relationship", characterId: "shen", amount: 5 }] },
          { id: "light", label: "笑说只是不慎划伤", next: "e", effects: [{ type: "relationship", characterId: "shen", amount: 2 }, { type: "set_flag", key: "memory.shen.hid_injury", value: true }] },
        ],
      },
      d: { id: "d", type: "line", speaker: "shen", text: "肯说实话便好。今晚少练一式，来问剑峰取药。", mood: "稍缓", next: "end" },
      e: { id: "e", type: "line", speaker: "shen", text: "你的笑话并不高明。罢了，药仍给你留着。", mood: "无奈", next: "end" },
      end: { id: "end", type: "end", summary: "沈清霜记下了你的伤势。" },
    },
  },
  {
    id: "shen.gift.snow-tea",
    title: "雪芽余温",
    subtitle: "一盏茶也能留下回声",
    chapter: "沈清霜 · 贰",
    type: "赠礼",
    trigger: "gift",
    priority: 85,
    once: true,
    journal: true,
    sceneId: "lingxiao",
    characterId: "shen",
    conditions: [
      { type: "scene", value: "lingxiao" },
      { type: "character", value: "shen" },
      { type: "gift", value: "snowTea" },
      { type: "event_completed", eventId: "shen.first.snow-in-hall" },
    ],
    clue: "将雪芽灵茶赠予沈清霜",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "shen", text: "寒峰雪芽……你从何处寻来的？", mood: "意外", next: "b" },
      b: { id: "b", type: "line", speaker: "player", text: "路过集市时想起师尊常饮清茶，便买下了。", next: "c" },
      c: { id: "c", type: "line", speaker: "shen", text: "不是常饮，是从前有人爱喝。如今……我也觉得尚可。", mood: "怀念", next: "end", effects: [{ type: "relationship", characterId: "shen", amount: 9 }, { type: "set_flag", key: "shen_received_snow_tea", value: true }] },
      end: { id: "end", type: "end", summary: "她将茶收进了贴身的储物玉中。" },
    },
  },
  {
    id: "shen.heart.moon-sword",
    title: "月下收剑",
    subtitle: "有人愿意等你停下",
    chapter: "沈清霜 · 叁",
    type: "情缘",
    trigger: "talk",
    priority: 95,
    once: true,
    journal: true,
    cardStyle: "special",
    openingEffect: "flash_white",
    defaultPortrait: "/assets/characters/shen-qingshuang.webp",
    sceneId: "lingxiao",
    characterId: "shen",
    conditions: [
      { type: "scene", value: "lingxiao" },
      { type: "character", value: "shen" },
      { type: "relationship", characterId: "shen", min: 16 },
      { type: "event_completed", eventId: "shen.gift.snow-tea" },
    ],
    clue: "与沈清霜缘分达到16，再与她交谈",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "shen", text: "今夜不讲剑诀。陪我坐一会儿。", mood: "柔和", next: "b", portrait: "/assets/characters/shen-qingshuang.webp", stageEffect: "soft_glow" },
      b: { id: "b", type: "line", speaker: "narrator", text: "她把两只茶盏放在石案上。你送的雪芽已经泡开，月色浮在杯沿。", next: "c", portrait: "/assets/characters/shen-qingshuang.webp", stageEffect: "soft_glow" },
      c: {
        id: "c",
        type: "choice",
        portrait: "/assets/characters/shen-qingshuang.webp",
        stageEffect: "heartbeat",
        options: [
          { id: "stay", label: "安静陪她看完月落", next: "d", effects: [{ type: "relationship", characterId: "shen", amount: 8 }] },
          { id: "ask", label: "问她方才想起了谁", next: "e", effects: [{ type: "relationship", characterId: "shen", amount: 4 }] },
        ],
      },
      d: { id: "d", type: "line", speaker: "shen", text: "你不问，我反而愿意说了。往后有些旧事，慢慢讲给你听。", next: "end", portrait: "/assets/characters/shen-qingshuang.webp", stageEffect: "heartbeat" },
      e: { id: "e", type: "line", speaker: "shen", text: "从前的自己。幸好，如今不必只想从前。", next: "end", portrait: "/assets/characters/shen-qingshuang.webp", stageEffect: "soft_glow" },
      end: { id: "end", type: "end", summary: "问剑峰的月色不再显得冷清。", portrait: "/assets/characters/shen-qingshuang.webp", stageEffect: "soft_glow" },
    },
  },
  {
    id: "su.first.wine-wager",
    title: "三问赌酒",
    subtitle: "师叔的玩笑总有半分认真",
    chapter: "苏晚棠 · 壹",
    type: "相识",
    trigger: "talk",
    priority: 80,
    once: true,
    journal: true,
    sceneId: "lingxiao",
    characterId: "su",
    conditions: [{ type: "scene", value: "lingxiao" }, { type: "character", value: "su" }],
    clue: "在凌霄殿与苏晚棠交谈",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "su", text: "来得正好。陪师叔赌一局——猜猜宗主方才为何叹气？", mood: "戏谑", next: "b" },
      b: {
        id: "b",
        type: "choice",
        options: [
          { id: "rules", label: "因为师叔又坏了规矩", next: "c", effects: [{ type: "relationship", characterId: "su", amount: 5 }] },
          { id: "wine", label: "因为他的好酒被人偷了", next: "d", effects: [{ type: "relationship", characterId: "su", amount: 4 }] },
        ],
      },
      c: { id: "c", type: "line", speaker: "su", text: "答得漂亮。可惜规矩那么多，谁知道是哪一条？", next: "end" },
      d: { id: "d", type: "line", speaker: "su", text: "嘘。你猜对得太具体，容易被当作同谋。", next: "end" },
      end: { id: "end", type: "end", summary: "你赢得了苏晚棠的一声轻笑。" },
    },
  },
  {
    id: "su.gift.peach-wine",
    title: "旧坛桃花",
    subtitle: "她认出了封泥上的年份",
    chapter: "苏晚棠 · 贰",
    type: "赠礼",
    trigger: "gift",
    priority: 85,
    once: true,
    journal: true,
    sceneId: "lingxiao",
    characterId: "su",
    conditions: [{ type: "character", value: "su" }, { type: "gift", value: "peachWine" }, { type: "event_completed", eventId: "su.first.wine-wager" }],
    clue: "将十年桃花酿赠予苏晚棠",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "su", text: "十年陈的桃花酿？这坛酒，可比你入门的年月还久。", mood: "惊喜", next: "b" },
      b: { id: "b", type: "line", speaker: "su", text: "今夜先不开。等有值得庆贺的事，我们一起。", mood: "认真", next: "end", effects: [{ type: "relationship", characterId: "su", amount: 9 }, { type: "set_flag", key: "su_saved_peach_wine", value: true }] },
      end: { id: "end", type: "end", summary: "她第一次没有当场打开一坛好酒。" },
    },
  },
  {
    id: "su.heart.plum-vow",
    title: "梅影同归",
    subtitle: "一场没有开坛的庆贺",
    chapter: "苏晚棠 · 叁",
    type: "情缘",
    trigger: "talk",
    priority: 95,
    once: true,
    journal: true,
    sceneId: "lingxiao",
    characterId: "su",
    conditions: [{ type: "character", value: "su" }, { type: "relationship", characterId: "su", min: 12 }, { type: "event_completed", eventId: "su.gift.peach-wine" }],
    clue: "与苏晚棠缘分达到12，再与她交谈",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "su", text: "那坛酒，我想好什么时候开了。", mood: "轻快", next: "b" },
      b: { id: "b", type: "line", speaker: "su", text: "等你下次远行平安归来。你回来，我便开坛。", mood: "认真", next: "c" },
      c: { id: "c", type: "line", speaker: "player", text: "若我不回来呢？", next: "d" },
      d: { id: "d", type: "line", speaker: "su", text: "那我就去把你带回来。酒与人，我都不喜欢久等。", next: "end", effects: [{ type: "relationship", characterId: "su", amount: 8 }] },
      end: { id: "end", type: "end", summary: "你们约定了一场归来后的酒。" },
    },
  },
  {
    id: "liu.first.herb-basket",
    title: "借宿医者",
    subtitle: "她先看见了你腕上的旧伤",
    chapter: "柳知意 · 壹",
    type: "相识",
    trigger: "talk",
    priority: 80,
    once: true,
    journal: true,
    sceneId: "tavern",
    characterId: "liu",
    conditions: [{ type: "scene", value: "tavern" }, { type: "character", value: "liu" }],
    clue: "在醉月楼与柳知意交谈",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "liu", text: "手给我。你腕上这道伤虽然愈合，寒气却还留在经脉里。", mood: "专注", next: "b" },
      b: {
        id: "b",
        type: "choice",
        options: [
          { id: "trust", label: "依言伸手", next: "c", effects: [{ type: "relationship", characterId: "liu", amount: 5 }] },
          { id: "joke", label: "问诊金能不能赊账", next: "d", effects: [{ type: "relationship", characterId: "liu", amount: 3 }] },
        ],
      },
      c: { id: "c", type: "line", speaker: "liu", text: "别紧张。三息便好……你很信任我？", mood: "微怔", next: "end" },
      d: { id: "d", type: "line", speaker: "liu", text: "可以。只是利息要按时服药来还。", mood: "浅笑", next: "end" },
      end: { id: "end", type: "end", summary: "柳知意为你记下了一张新药方。" },
    },
  },
  {
    id: "liu.gift.herb-sachet",
    title: "草木安眠",
    subtitle: "医者也会收到安神之物",
    chapter: "柳知意 · 贰",
    type: "赠礼",
    trigger: "gift",
    priority: 85,
    once: true,
    journal: true,
    sceneId: "tavern",
    characterId: "liu",
    conditions: [{ type: "character", value: "liu" }, { type: "gift", value: "herbSachet" }, { type: "event_completed", eventId: "liu.first.herb-basket" }],
    clue: "将紫苏安神囊赠予柳知意",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "liu", text: "紫苏、合欢皮，还有一点夜交藤……配得很好。", mood: "欣喜", next: "b" },
      b: { id: "b", type: "line", speaker: "player", text: "医者也该有人提醒她休息。", next: "c" },
      c: { id: "c", type: "line", speaker: "liu", text: "那今晚我听你的。只看完最后两页医案便睡。", mood: "温柔", next: "end", effects: [{ type: "relationship", characterId: "liu", amount: 9 }] },
      end: { id: "end", type: "end", summary: "香囊被她系在了最常用的药箱上。" },
    },
  },
  {
    id: "liu.heart.pulse",
    title: "脉上春声",
    subtitle: "她忽然分不清是谁心跳更快",
    chapter: "柳知意 · 叁",
    type: "情缘",
    trigger: "talk",
    priority: 95,
    once: true,
    journal: true,
    sceneId: "tavern",
    characterId: "liu",
    conditions: [{ type: "character", value: "liu" }, { type: "relationship", characterId: "liu", min: 12 }, { type: "event_completed", eventId: "liu.gift.herb-sachet" }],
    clue: "与柳知意缘分达到12，再与她交谈",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "liu", text: "今日再诊一次脉。上次那道寒气，我有些在意。", next: "b" },
      b: { id: "b", type: "line", speaker: "narrator", text: "她的指尖落在腕间，片刻后却像被烫到似的移开。", next: "c" },
      c: { id: "c", type: "line", speaker: "liu", text: "脉象……无碍。大约是楼里太热了。", mood: "慌乱", next: "d" },
      d: { id: "d", type: "line", speaker: "player", text: "可你的耳朵也红了。", next: "e" },
      e: { id: "e", type: "line", speaker: "liu", text: "那便是另一种病。暂时……没有药方。", mood: "羞赧", next: "end", effects: [{ type: "relationship", characterId: "liu", amount: 8 }] },
      end: { id: "end", type: "end", summary: "她把诊脉的时间延长了很久。" },
    },
  },
  {
    id: "hua.first.welcome",
    title: "灯下新客",
    subtitle: "老板娘替你留了临窗的位置",
    chapter: "花照影 · 壹",
    type: "相识",
    trigger: "scene_enter",
    priority: 90,
    once: true,
    journal: true,
    sceneId: "tavern",
    characterId: "hua",
    conditions: [{ type: "scene", value: "tavern" }],
    clue: "初次踏入醉月楼",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "hua", text: "这位仙长，是喝酒、听消息，还是躲雨？", mood: "含笑", next: "b" },
      b: {
        id: "b",
        type: "choice",
        options: [
          { id: "see", label: "来见老板娘", next: "c", effects: [{ type: "relationship", characterId: "hua", amount: 6 }] },
          { id: "all", label: "三样都要", next: "d", effects: [{ type: "relationship", characterId: "hua", amount: 4 }] },
        ],
      },
      c: { id: "c", type: "line", speaker: "hua", text: "嘴甜的客人，第一杯通常免费。第二杯可就要收利息了。", next: "end" },
      d: { id: "d", type: "line", speaker: "hua", text: "胃口不小。坐窗边吧，那张桌子今日恰好没人。", next: "end" },
      end: { id: "end", type: "end", summary: "醉月楼为你留下一张临窗小桌。" },
    },
  },
  {
    id: "hua.gift.hairpin",
    title: "海棠照影",
    subtitle: "金簪在她掌心泛起灯色",
    chapter: "花照影 · 贰",
    type: "赠礼",
    trigger: "gift",
    priority: 85,
    once: true,
    journal: true,
    sceneId: "tavern",
    characterId: "hua",
    conditions: [{ type: "character", value: "hua" }, { type: "gift", value: "goldHairpin" }, { type: "event_completed", eventId: "hua.first.welcome" }],
    clue: "将金丝海棠簪赠予花照影",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "hua", text: "海棠簪？你可知道，送簪子在山下是什么意思？", mood: "试探", next: "b" },
      b: {
        id: "b",
        type: "choice",
        options: [
          { id: "know", label: "知道，所以才送", next: "c", effects: [{ type: "relationship", characterId: "hua", amount: 10 }] },
          { id: "learn", label: "不知道，愿闻其详", next: "d", effects: [{ type: "relationship", characterId: "hua", amount: 7 }] },
        ],
      },
      c: { id: "c", type: "line", speaker: "hua", text: "那我便收得明明白白。日后可不许赖账。", mood: "动容", next: "end" },
      d: { id: "d", type: "line", speaker: "hua", text: "不知道更好。等你想明白了，再来问我。簪子我先收下。", mood: "从容", next: "end" },
      end: { id: "end", type: "end", summary: "第二日，那支簪便出现在了她发间。" },
    },
  },
  {
    id: "hua.heart.closed-tavern",
    title: "闭门留灯",
    subtitle: "今夜最后一盏灯只为一人",
    chapter: "花照影 · 叁",
    type: "情缘",
    trigger: "talk",
    priority: 95,
    once: true,
    journal: true,
    sceneId: "tavern",
    characterId: "hua",
    conditions: [{ type: "character", value: "hua" }, { type: "relationship", characterId: "hua", min: 14 }, { type: "event_completed", eventId: "hua.gift.hairpin" }],
    clue: "与花照影缘分达到14，再与她交谈",
    start: "a",
    nodes: {
      a: { id: "a", type: "line", speaker: "hua", text: "今夜打烊得早。不是赶你，是想问你要不要留下。", mood: "认真", next: "b" },
      b: { id: "b", type: "line", speaker: "narrator", text: "她卸下白日里滴水不漏的笑意，将账本推到一旁。发间正是你送的海棠簪。", next: "c" },
      c: { id: "c", type: "line", speaker: "hua", text: "我听过太多人的故事。今晚，换你听听我的。", next: "d" },
      d: { id: "d", type: "line", speaker: "player", text: "我不急。你可以慢慢说。", next: "e" },
      e: { id: "e", type: "line", speaker: "hua", text: "这句话，比任何承诺都值钱。", mood: "释然", next: "end", effects: [{ type: "relationship", characterId: "hua", amount: 8 }] },
      end: { id: "end", type: "end", summary: "醉月楼闭门后，你听见了她未曾售卖的往事。" },
    },
  },
  {
    id:"hua.egg.old-wine-token",title:"柜脚下的旧酒筹",subtitle:"醉月楼里没人认领的一段小秘密",chapter:"花照影 · 彩蛋",type:"闲谈",trigger:"scene_enter",priority:42,weight:1,once:true,journal:true,cardStyle:"easter_egg",sceneId:"tavern",characterId:"hua",
    conditions:[{type:"scene",value:"tavern"},{type:"event_completed",eventId:"hua.first.welcome"}],clue:"进入醉月楼后，留意柜台附近偶尔亮起的金色微光",start:"end",
    exploration:{chance:80,positionMode:"random",image:"/assets/scenes/drunken-moon-tavern.webp",text:"柜脚与地板的缝隙里压着一枚旧酒筹，背面刻着一朵极小的海棠。花照影看见后只笑了笑，说这是某位客人许多年前欠下的一杯酒。",rewardItem:{id:"old-wine-token",name:"海棠旧酒筹",image:"/assets/scenes/drunken-moon-tavern.webp",description:"边缘已经磨得圆润。背面的海棠刻痕，似乎与老板娘从不提起的往事有关。"}},
    nodes:{end:{id:"end",type:"end",summary:"海棠旧酒筹已经收入藏珍录。"}},
  },
  {
    id:"shen.trigger.eaves-sword",title:"檐角剑鸣",subtitle:"无人触碰的剑穗忽然自行摇动",chapter:"沈清霜 · 隐迹",type:"心事",trigger:"scene_enter",priority:72,weight:1,once:true,journal:true,cardStyle:"trigger_point",sceneId:"lingxiao",characterId:"shen",
    conditions:[{type:"scene",value:"lingxiao"},{type:"event_completed",eventId:"shen.first.snow-in-hall"}],clue:"凌霄殿偶尔会出现一枚青色异光，触碰后可进入隐藏剧情",start:"a",
    exploration:{chance:100,positionMode:"random",image:"/assets/scenes/lingxiao-hall.webp",text:"檐角悬着一缕几乎透明的剑气。它并不伤人，只在你靠近时发出一声极轻的剑鸣，像是在等待某个能听懂它的人。"},
    nodes:{a:{id:"a",type:"line",speaker:"narrator",text:"你伸手触及青色微光，积雪之下随即浮出一道浅淡剑痕。",next:"b"},b:{id:"b",type:"line",speaker:"shen",text:"这是师父留下的问心剑意。它既然回应你，便说明你心中并无欺瞒。",mood:"意外",next:"c"},c:{id:"c",type:"line",speaker:"player",text:"若我心中藏着未说出口的话呢？",next:"d"},d:{id:"d",type:"line",speaker:"shen",text:"未说出口与有意欺瞒，并非一回事。等你愿意时，我会听。",mood:"柔和",next:"end",effects:[{type:"relationship",characterId:"shen",amount:3}]},end:{id:"end",type:"end",summary:"檐角的剑鸣渐渐归于寂静。"}},
  },
  {
    id:"shen.memory.injury-callback",title:"旧伤未忘",subtitle:"她记得你曾经避开的目光",chapter:"人物记忆",type:"闲谈",trigger:"talk",priority:93,once:true,journal:false,sceneId:"lingxiao",characterId:"shen",
    conditions:[{type:"character",value:"shen"},{type:"event_completed",eventId:"shen.first.snow-in-hall"},{type:"flag",key:"memory.shen.hid_injury",value:true}],clue:"沈清霜会记得你曾隐瞒伤势",start:"a",
    nodes:{a:{id:"a",type:"line",speaker:"shen",text:"上次你说只是划伤，后来我看过剑场的血迹。你若不愿说，我不会逼你；但别再独自忍着。",mood:"认真",next:"b"},b:{id:"b",type:"line",speaker:"player",text:"原来你一直记得。",next:"end",effects:[{type:"relationship",characterId:"shen",amount:2}]},end:{id:"end",type:"end",summary:"她没有追问，却从未忘记。"}},
  },
  {
    id:"hua.map.crimson-lantern",title:"赤灯照旧约",subtitle:"一盏不属于今夜的灯在山河图上亮起",chapter:"花照影 · 地图异闻",type:"心事",trigger:"map_event",priority:100,once:true,journal:true,cardStyle:"special",openingEffect:"flash_black",defaultPortrait:"/assets/characters/hua-zhaoying.webp",sceneId:"tavern",characterId:"hua",
    mapEvent:{mapId:"yunzhou",windowDays:10,x:47,y:65},conditions:[{type:"relationship",characterId:"hua",min:4}],clue:"前置条件达成后，未来十日内留意云州地图上的金红异光",start:"a",
    nodes:{a:{id:"a",type:"line",speaker:"narrator",text:"你触到山河图上的赤色光标，眼前骤然一暗。再睁眼时，醉月楼已经打烊，檐下一盏旧灯却仍在等人。",next:"b",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"soft_glow"},b:{id:"b",type:"line",speaker:"hua",text:"这盏灯十年前就该熄了。既然被你看见，便替我陪它等完今夜吧。",mood:"怀念",next:"c",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"heartbeat"},c:{id:"c",type:"choice",prompt:"你望向灯下的她。",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"heartbeat",options:[{id:"stay",label:"不问旧事，只陪她守灯",next:"d",effects:[{type:"relationship",characterId:"hua",amount:6}]},{id:"promise",label:"若那人不来，往后的灯由我来点",next:"e",effects:[{type:"relationship",characterId:"hua",amount:8}]}]},d:{id:"d",type:"line",speaker:"hua",text:"你安静的时候，倒比会说话时更讨人喜欢。",mood:"释然",next:"end",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"soft_glow"},e:{id:"e",type:"line",speaker:"hua",text:"这话我记下了。山下人的承诺，可没有反悔这一说。",mood:"动容",next:"end",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"heartbeat"},end:{id:"end",type:"end",summary:"天明前，旧灯终于熄灭；她却将新的灯芯交到了你手中。",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"soft_glow"}},
  },
  {
    id:"shen.calendar.birthday",title:"霜华生辰",subtitle:"师尊从不提起的生辰，被你记在了云和历上",chapter:"沈清霜 · 生辰",type:"情缘",trigger:"calendar_event",priority:120,once:false,journal:true,cardStyle:"special",openingEffect:"flash_white",defaultPortrait:"/assets/characters/shen-qingshuang.webp",sceneId:"lingxiao",characterId:"shen",
    calendarEvent:{mode:"fixed",month:1,day:8,doodle:"birthday"},conditions:[{type:"relationship",characterId:"shen",min:4}],clue:"每年正月初八，沈清霜缘分达到4后触发",start:"a",
    nodes:{a:{id:"a",type:"line",speaker:"narrator",text:"正月初八，问剑峰的雪比往日更静。你在石案上放下一碗亲手做的长寿面。",next:"b",portrait:"/assets/characters/shen-qingshuang.webp",stageEffect:"soft_glow"},b:{id:"b",type:"line",speaker:"shen",text:"修行之人不重生辰。只是……既然你记得，便坐下一同吃吧。",mood:"动容",next:"end",portrait:"/assets/characters/shen-qingshuang.webp",stageEffect:"heartbeat",effects:[{type:"relationship",characterId:"shen",amount:5}]},end:{id:"end",type:"end",summary:"雪落无声，她却把这一天留在了心里。",portrait:"/assets/characters/shen-qingshuang.webp",stageEffect:"soft_glow"}},
  },
  {
    id:"hua.calendar.qiqiao",title:"乞巧灯约",subtitle:"七月七日，山下灯河照见未说出口的心愿",chapter:"花照影 · 乞巧",type:"情缘",trigger:"calendar_event",priority:110,once:false,journal:true,cardStyle:"special",openingEffect:"flash_black",defaultPortrait:"/assets/characters/hua-zhaoying.webp",sceneId:"tavern",characterId:"hua",
    calendarEvent:{mode:"fixed",month:7,day:7,doodle:"festival"},conditions:[{type:"event_completed",eventId:"hua.first.welcome"}],clue:"每年七月初七，完成「灯下新客」后触发",start:"a",
    nodes:{a:{id:"a",type:"line",speaker:"hua",text:"今夜的灯不能收钱，只能拿愿望来换。你若肯说一个，我便陪你放一盏。",mood:"含笑",next:"b",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"soft_glow"},b:{id:"b",type:"line",speaker:"player",text:"愿明年今日，仍有人与我并肩看灯。",next:"c",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"heartbeat"},c:{id:"c",type:"line",speaker:"hua",text:"这愿望太贪心。不过，我准了。",mood:"温柔",next:"end",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"heartbeat",effects:[{type:"relationship",characterId:"hua",amount:6}]},end:{id:"end",type:"end",summary:"两盏灯并在一处，顺着长河漂向远方。",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"soft_glow"}},
  },
  {
    id:"shen.inspect.sword-shadow",title:"月下剑影",subtitle:"夜色里多出了一道不属于你的剑影",chapter:"沈清霜 · 检视",type:"心事",trigger:"inspection",priority:90,once:true,journal:true,cardStyle:"special",openingEffect:"flash_white",defaultPortrait:"/assets/characters/shen-qingshuang.webp",inspection:{chance:65,hint:true},sceneId:"lingxiao",characterId:"shen",
    conditions:[{type:"relationship",characterId:"shen",min:8},{type:"event_completed",eventId:"shen.first.snow-in-hall"}],clue:"夜晚检视凌霄殿；地图上会显出眼睛提示",start:"a",
    nodes:{a:{id:"a",type:"line",speaker:"narrator",text:"云雾从石阶两侧退开，一道清寒剑影恰好收势。沈清霜本不该在这个时辰仍留在殿前。",next:"b",stageEffect:"soft_glow"},b:{id:"b",type:"line",speaker:"shen",text:"睡不着，便来走一遍旧剑式。你既看见了，就替我守住这个秘密。",mood:"稍显疲惫",next:"end",effects:[{type:"relationship",characterId:"shen",amount:4}],stageEffect:"heartbeat"},end:{id:"end",type:"end",summary:"月下剑影被重新收进了夜色。"}},
  },
  {
    id:"hua.inspect.back-lantern",title:"后窗余灯",subtitle:"打烊后的灯影里藏着一句没说完的话",chapter:"花照影 · 检视",type:"心事",trigger:"inspection",priority:82,once:true,journal:true,inspection:{chance:55,hint:true},sceneId:"tavern",characterId:"hua",
    conditions:[{type:"relationship",characterId:"hua",min:8},{type:"event_completed",eventId:"hua.first.welcome"}],clue:"夜晚检视醉月楼；地图上会显出眼睛提示",start:"a",
    nodes:{a:{id:"a",type:"line",speaker:"narrator",text:"云雾散去，后窗仍留着一盏灯。花照影伏在账册上睡着了，手边压着一封只写了称谓的信。",next:"b"},b:{id:"b",type:"choice",prompt:"你打算如何做？",options:[{id:"cloak",label:"替她披上外衣，不看信笺",next:"c",effects:[{type:"relationship",characterId:"hua",amount:5}]},{id:"wake",label:"轻声唤醒她",next:"d",effects:[{type:"relationship",characterId:"hua",amount:3}]}]},c:{id:"c",type:"line",speaker:"hua",text:"装睡的人也会知道是谁替她披的衣裳。",mood:"含笑",next:"end"},d:{id:"d",type:"line",speaker:"hua",text:"被你撞见这副样子，今夜的酒钱可得加倍。",mood:"慵懒",next:"end"},end:{id:"end",type:"end",summary:"那封未写完的信仍留在灯下。"}},
  },
  {
    id:"shen.inspect.bedroom-letter",title:"窗外纸鹤",subtitle:"一只不肯惊动你的传信纸鹤",chapter:"沈清霜 · 隐秘检视",type:"情缘",trigger:"inspection",priority:95,once:true,journal:true,inspection:{chance:35,hint:false},sceneId:"bedroom",characterId:"shen",
    conditions:[{type:"relationship",characterId:"shen",min:18},{type:"event_completed",eventId:"shen.gift.snow-tea"}],clue:"夜晚检视自己的居所；此事件不会显示眼睛提示",start:"a",
    nodes:{a:{id:"a",type:"line",speaker:"narrator",text:"窗前云雾被风拨开，一只纸鹤停在窗棂外。它似乎徘徊了很久，翅尖已经沾湿。",next:"b"},b:{id:"b",type:"line",speaker:"shen",text:"夜深风冷。练功之后记得关窗……若仍无睡意，可以来问剑峰。",mood:"克制的关心",next:"end",effects:[{type:"relationship",characterId:"shen",amount:5}]},end:{id:"end",type:"end",summary:"你将纸鹤收在枕边，整夜都没有再开窗。"}},
  },
  {
    id:"hua.drinking.three-cups",title:"三杯照心",subtitle:"酒意未深，藏了许久的话却先出了口",chapter:"花照影 · 夜酌",type:"情缘",trigger:"interaction",interactionId:"drinking",priority:130,once:true,journal:true,cardStyle:"special",openingEffect:"flash_black",defaultPortrait:"/assets/characters/hua-zhaoying.webp",sceneId:"tavern",characterId:"hua",
    conditions:[{type:"scene",value:"tavern"},{type:"period",value:"夜晚"},{type:"relationship",characterId:"hua",min:15}],clue:"夜晚在醉月楼与花照影共饮，累计三次共饮成功",start:"a",
    nodes:{a:{id:"a",type:"line",speaker:"narrator",text:"第三只酒杯落回桌面，灯花恰在此时轻轻一爆。花照影没有再斟酒，只将自己的杯子推到你面前。",next:"b",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"soft_glow"},b:{id:"b",type:"line",speaker:"hua",text:"三杯都接得这样稳。那我接下来要说的话，你也得稳稳接住。",mood:"微醺",next:"c",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"heartbeat"},c:{id:"c",type:"choice",prompt:"她隔着摇曳灯火看向你。",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"heartbeat",options:[{id:"listen",label:"放下酒杯，认真听她说",next:"d",effects:[{type:"relationship",characterId:"hua",amount:8}]},{id:"closer",label:"将她的酒杯也一并饮尽",next:"e",effects:[{type:"relationship",characterId:"hua",amount:10}]}]},d:{id:"d",type:"line",speaker:"hua",text:"我见过很多人借酒说真话。可你清醒着听，反倒让我更安心。",mood:"动容",next:"end",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"soft_glow"},e:{id:"e",type:"line",speaker:"hua",text:"喝了我的酒，便算应下了。往后醉月楼最后一盏灯，都替你留着。",mood:"含笑",next:"end",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"heartbeat"},end:{id:"end",type:"end",summary:"酒香散尽时，你们之间多了一句不必说破的约定。",portrait:"/assets/characters/hua-zhaoying.webp",stageEffect:"soft_glow"}},
  },
];

SCENES.push(...SHOP_SCENES);
GIFTS.push(...SHOP_GIFTS);
CHARACTERS.push(...SHOP_CHARACTERS);
CHARACTER_MESSAGES.push(...SHOP_MESSAGES);
EVENTS.push(...SHOP_EVENTS);

export const CHARACTER_MAP = Object.fromEntries(CHARACTERS.map((character) => [character.id, character])) as Record<(typeof CHARACTERS)[number]["id"], CharacterDefinition>;
export const SCENE_MAP = Object.fromEntries(SCENES.map((scene) => [scene.id, scene])) as Record<(typeof SCENES)[number]["id"], SceneDefinition>;
export const GIFT_MAP = Object.fromEntries(GIFTS.map((gift) => [gift.id, gift])) as Record<(typeof GIFTS)[number]["id"], GiftDefinition>;
