import { GATHERING_COMPANION_POOLS, GATHERING_LEVEL_THRESHOLDS, gatheringProfession } from "./content";
import type { GatheringCareerState, GatheringOutcomeInput, GatheringProfessionId, GatheringProgress, GatheringRarity } from "./types";

const STARTING_TOOLS:Record<GatheringProfessionId,string>={fishing:"willow-rod",farming:"green-hoe",mining:"iron-pick"};
function initialCareer(id:GatheringProfessionId):GatheringCareerState{return{experience:0,toolTier:1,selectedToolId:STARTING_TOOLS[id],discoveries:{},displayed:{},harvestCount:0,processedCount:0};}
export function createInitialGathering():GatheringProgress{return{careers:{fishing:initialCareer("fishing"),farming:initialCareer("farming"),mining:initialCareer("mining")}};}
export function normalizeGathering(value?:Partial<GatheringProgress>|null):GatheringProgress{const base=createInitialGathering();return{careers:Object.fromEntries((Object.keys(base.careers) as GatheringProfessionId[]).map(id=>[id,{...base.careers[id],...value?.careers?.[id],discoveries:{...value?.careers?.[id]?.discoveries},displayed:{...value?.careers?.[id]?.displayed}}])) as GatheringProgress["careers"]};}
export function gatheringLevel(experience:number){let level=1;for(let index=1;index<GATHERING_LEVEL_THRESHOLDS.length;index+=1)if(experience>=GATHERING_LEVEL_THRESHOLDS[index])level=index+1;return Math.min(10,level);}
export function gatheringLevelProgress(experience:number){const level=gatheringLevel(experience),start=GATHERING_LEVEL_THRESHOLDS[level-1]??0,end=GATHERING_LEVEL_THRESHOLDS[level]??start;return{level,current:experience-start,needed:Math.max(0,end-start),percentage:end===start?100:Math.min(100,(experience-start)/(end-start)*100)};}
export function selectedTool(id:GatheringProfessionId,career:GatheringCareerState){const profession=gatheringProfession(id);return profession.tools.find(tool=>tool.id===career.selectedToolId)??profession.tools[0];}
function hash(seed:string){let value=2166136261;for(let i=0;i<seed.length;i+=1)value=Math.imul(value^seed.charCodeAt(i),16777619);return(value>>>0)/4294967296;}
function clampRarity(value:number):GatheringRarity{return Math.max(1,Math.min(5,Math.round(value))) as GatheringRarity;}
export function companionChance(professionId:GatheringProfessionId,career:GatheringCareerState){const level=gatheringLevel(career.experience),trait=selectedTool(professionId,career).trait;return Math.min(.25,.10+(level-1)*.008+(career.toolTier-1)*.012+(trait==="treasure"?.045:trait==="character"?.018:0));}
function rollCompanion(professionId:GatheringProfessionId,career:GatheringCareerState,seed:string){if(hash(`${seed}:companion`)>=companionChance(professionId,career))return null;const pool=GATHERING_COMPANION_POOLS[professionId].filter(item=>item.rarity<=Math.min(5,career.toolTier+1));const total=pool.reduce((sum,item)=>sum+item.weight,0);let roll=hash(`${seed}:pool`)*total;for(const item of pool){roll-=item.weight;if(roll<=0)return item;}return pool.at(-1)??null;}
export function resolveGatheringOutcome(progress:GatheringProgress,input:GatheringOutcomeInput){const career=progress.careers[input.professionId],rarity=clampRarity(input.rarity),firstDiscovery=!career.discoveries[input.itemId],tool=selectedTool(input.professionId,career);const experience=3+rarity*2+(firstDiscovery?6:0)+(tool.trait==="character"&&firstDiscovery?4:0);const discovery={itemId:input.itemId,name:input.name,rarity,art:input.art,location:input.location,tags:[...new Set(input.tags)],discoveredAtTick:input.tick};const companion=rollCompanion(input.professionId,career,input.seed);const companionDiscovery=companion?{itemId:companion.id,name:companion.name,rarity:clampRarity(companion.rarity),art:companion.art,location:input.location,tags:companion.tags,discoveredAtTick:input.tick}:null;const nextCareer:GatheringCareerState={...career,experience:career.experience+experience,harvestCount:career.harvestCount+1,discoveries:{...career.discoveries,[discovery.itemId]:discovery,...(companionDiscovery?{[companionDiscovery.itemId]:companionDiscovery}:{})}};return{progress:{...progress,careers:{...progress.careers,[input.professionId]:nextCareer}},experience,firstDiscovery,companion,companionChance:companionChance(input.professionId,career)};}
